version: '3.8'
services:
  registry-discovery:
    container_name: ms-eureka
    image: microservices/ms-eureka:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    # networks:
    #   - taller

######################################################

  configuration:
    container_name: config-server
    image: microservices/ms-config-server:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -DLOCAL_REPOSITORY=https://github.com/JoseMontesU/service-configuration
    depends_on:
      - registry-discovery
    ports:
      - 8888:8888
    # networks:
    #   - taller

#######################################################

  person-microservice:
    container_name: ms-person
    image: microservices/ms-person:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -DWORK_ENV=production
#        -DWORK_ENV=development
#        -Dspring.profiles.active=production
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - 8081:8081
    # networks:
    #   - taller

##########################################################

  mysql:
    image: mysql:8.0
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: neo.123
      MYSQL_DATABASE: tallerdb
    ports:
      - 3306:3306
    # networks:
    #   - taller
########################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=neo.123
      - PMA_HOST=mysql
    ports:
      - '8078:80'
    depends_on:
      - mysql

################# Keycloak CON MYSQL ########################
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloakServer
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/tallerdb
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: neo.123
      KC_HOSTNAME: localhost
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./config_realm/:/opt/keycloak/data/import:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
    # networks:
    #   - taller

