version: '3.8'
services:
  registry-discovery:
    container_name: ms-eureka
    image: microservices/ms-eureka:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M

######################################################

  configuration:
    container_name: config-server
    image: microservices/ms-config-server:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -DLOCAL_REPOSITORY=https://github.com/JoseMontesU/service-configuration
    depends_on:
      - registry-discovery
    ports:
      - 8888:8888

#######################################################

  person-microservice:
    container_name: ms-person
    image: microservices/ms-person:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -DWORK_ENV=production
#        -DWORK_ENV=development
#        -Dspring.profiles.active=production
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - 8081:8081

##########################################################

  db:
    image: mysql:8.0
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: neo.123
      MYSQL_DATABASE: tallerdb
    ports:
      - 3306:3306

###########################################################

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: keycloakServer
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./config_realm/:/opt/keycloak/data/import:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
